name: opsd_time_series

dependencies:
  - python=3.6
  - pandas
  - numpy
  - xlrd  # pandas: excel i/o
  - openpyxl  # pandas: excel i/o
  - bottleneck  # accelerates some pandas operations
  - numexpr  # accelerates some pandas operations
  - notebook  # jupyter notebook
  - pyyaml
  - requests
  - jupyter_contrib_nbextensions  # nice add-ons for jupyter
  